<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>disable</Nullable>
        <MicroComGeneratorRuntimeNamespace>MicroCom.Runtime</MicroComGeneratorRuntimeNamespace>
        <PackageId>FluentAvaloniaUI.Qianyiaz</PackageId>
        <IsAotCompatible>true</IsAotCompatible>
        <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
        <NoWarn>$(NoWarn);NU1507</NoWarn>
    </PropertyGroup>

    <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|AnyCPU'">
        <GeneratePackageOnBuild>true</GeneratePackageOnBuild>
        <GenerateDocumentationFile>true</GenerateDocumentationFile>
    </PropertyGroup>

    <ItemGroup>
        <AvaloniaResource Include="Fonts\*.*"/>
        <PackageReference Include="Avalonia.Controls.ColorPicker"/>
        <PackageReference Include="Avalonia.Skia"/>
        <PackageReference Include="MicroCom.CodeGenerator.MSBuild" PrivateAssets="All"/>
        <MicroComIdl Include="$(MSBuildThisFileDirectory)\Interop\WinRT\WinRT.idl" CSharpInteropPath="$(MSBuildThisFileDirectory)\Interop\WinRT\WinRT.Generated.cs"/>
    </ItemGroup>

    <ItemGroup>
        <InternalsVisibleTo Include="FAControlsGallery"/>
    </ItemGroup>
</Project>
